# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0002_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='desc',
            new_name='title',
        ),
    ]
