# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0003_auto_20181025_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='desc',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
