# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0005_archive_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/$D/'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/$D/'),
        ),
    ]
