# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-27 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0006_auto_20181026_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='desc',
        ),
    ]
